### ISSUE TITLE
Join accelerator community

### ISSUE THREAD

**Issue by goatandsheep** [Guidebolt/avatar-team#24]
Ideally it is tied to a university. Ideally the university of choice

**Comment by Lexora** [comment]
I talked to Eric Dyer who's recently completed his masters at Mac (was a biomed friend in my year) and he's interested in project, furthermore he thought it would not be a bad idea to talk to his super, who... "when it comes to haptics and feedback, **sirouspour** is the guy"

**Comment by goatandsheep** [comment]
Is it okay that McMaster is far? I mean are we willing to have meetings multiple times per week in Hamilton? I was thinking Ryerson would be ideal. What do you think?

**Comment by openyk** [comment]
Is joining multiple communities and leveraging VOIP too impractical?

**Comment by goatandsheep** [comment]
I think it'll be better just to be a part of one community:
1. We can associate ourselves as being part of the community
2. market and recruit more easily
3. Executive body will be tough to form
4. Connecting multiple communities will be difficult if we want to be a guild and be able to support the community
5. Schools will be more willing to identify with us

**Comment by openyk** [comment]
Sounds like a sensible start.
