### ISSUE TITLE
Affiliate links

### ISSUE THREAD

**Issue by goatandsheep** [Guidebolt/avatar-team#25]
Is it unethical to create affiliate links to the technologies we are using? If we can show that we're linking to products, it is more likely that we will be viewed by potential sponsors.

**Comment by openyk** [comment]
It's an interesting trade-off. People may trust us more if we don't have any direct vested interest in whether they purchase a recommended product or not. Conversely, providing quick links are convenient for users and an affiliate code would be necessary to provide key metrics to sponsors, who like to see quantified results.

**Comment by openyk** [comment]
Affiliate links seem ethical as long as their use doesn't distort our recommendation standards at all. Then there's the topic of efficiency in generating/managing affiliate links, etc. Which is a hassle.

**Comment by goatandsheep** [comment]
I totally agree: we won't maintain any names that we don't agree with
