### ISSUE TITLE
Onboarding Strategy

### ISSUE THREAD

**Issue by openyk** [Guidebolt/avatar-team#33]

**Comment by openyk** [comment]
Key parts of the first interview should ask what they are interested in, what they can/want to contribute to, and what commitment level they would like to uphold. Checking their alignment with the pillar principles of the guild is significant.

Once they pass the interview, we should invite them into the guildchat, maybe after having them complete a task.

**Comment by goatandsheep** [comment]
what can we declare as "pillar principles"?
