### ISSUE TITLE
Think of at least 3 niches

### ISSUE THREAD

**Issue by goatandsheep** [Guidebolt/avatar-team#4]
- [x] list niches
- [ ] discuss niches
- [ ] choose target niches

**Comment by openyk** [comment]
1. General-purpose personal use (buy and carry groceries, organize heavy items, do laundry)
2. Security use (private security, police, military)
3. Remote work/assistance (provide plumbing help, medical help, respond to friends/family/connected communities instantly for emergency assistance)
